site_name: FactorEngine Docs
repo_url: https://github.com/your-org/factorengine
theme:
  name: material
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Usage: usage.md
  - Benchmarking: benchmarking.md
  - Deployment: deployment.md
  - Symbiosis: symbiosis.md
  - Glossary: ../Glossary.md