name: Enforce Coverage

on: [push, pull_request]

jobs:
  coverage-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run coverage
      run: |
        coverage run -m pytest tests/
        coverage report --fail-under=80
