name: Deploy Docs

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          python -m pip install mkdocs mkdocs-material
          mkdocs build
      - uses: squidfunk/[email protected]
        with:
          publish_branch: gh-pages
          force_orphan: true
