name: Lint & Format
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort mypy
      - name: Black format check
        run: black --check .
      - name: isort check
        run: isort . --check
      - name: flake8 lint
        run: flake8 .
      - name: mypy type check
        run: mypy .
